# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('applicant_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('applicant_name', models.CharField(max_length=32)),
                ('apply_department', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
    ]
