# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mysite', '0002_delete_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application_Model',
            fields=[
                ('applicant_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('applicant_name', models.CharField(max_length=32)),
                ('apply_department', models.CharField(choices=[(b'1', b'A'), (b'2', b'B'), (b'3', b'C'), (b'4', b'D'), (b'5', b'E')], max_length=12)),
                ('reason', models.TextField()),
            ],
        ),
    ]
