# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_application_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Application_Model')),
            ],
        ),
        migrations.CreateModel(
            name='Manager_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Member_Model',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('costs', models.PositiveSmallIntegerField(default=0)),
                ('nick_name', models.CharField(max_length=20, null=True)),
                ('department', models.CharField(max_length=15, null=True)),
                ('phone_number', models.CharField(max_length=11, null=True)),
                ('address', models.CharField(max_length=10, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Application_Model')),
            ],
        ),
        migrations.AddField(
            model_name='manager_model',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Member_Model'),
        ),
        migrations.AddField(
            model_name='code',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Manager_Model'),
        ),
    ]
