# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20170718_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_model',
            name='apply_department',
            field=models.CharField(choices=[('\u79d8\u4e66\u90e8', b'\xe7\xa7\x98\xe4\xb9\xa6\xe9\x83\xa8'), ('\u4eba\u529b\u8d44\u6e90\u90e8', b'\xe4\xba\xba\xe5\x8a\x9b\xe8\xb5\x84\xe6\xba\x90\xe9\x83\xa8'), ('\u5ba3\u4f20\u90e8', b'\xe5\xae\xa3\xe4\xbc\xa0\xe9\x83\xa8'), ('\u7ec4\u7ec7\u90e8', b'\xe7\xbb\x84\xe7\xbb\x87\xe9\x83\xa8')], default=b'\xe7\xa7\x98\xe4\xb9\xa6\xe9\x83\xa8', max_length=12),
        ),
        migrations.AlterField(
            model_name='member_model',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
