# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20170719_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code_Model',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Manager_Model')),
            ],
        ),
        migrations.RemoveField(
            model_name='code',
            name='email',
        ),
        migrations.RemoveField(
            model_name='code',
            name='member_id',
        ),
        migrations.DeleteModel(
            name='Code',
        ),
    ]
