# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20170719_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Model',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe5\x8f\x91\xe8\xa1\xa8\xe6\x97\xb6\xe9\x97\xb4')),
                ('theme', models.CharField(max_length=128)),
                ('section', models.CharField(choices=[('\u677f\u57571', b'\xe6\x9d\xbf\xe5\x9d\x971'), ('\u677f\u57572', b'\xe6\x9d\xbf\xe5\x9d\x972'), ('\u677f\u57573', b'\xe6\x9d\xbf\xe5\x9d\x973'), ('\u677f\u57574', b'\xe6\x9d\xbf\xe5\x9d\x974')], default=b'\xe6\x9d\xbf\xe5\x9d\x971', max_length=12)),
                ('content', models.CharField(max_length=10240)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Member_Model')),
            ],
        ),
        migrations.AlterField(
            model_name='application_model',
            name='apply_department',
            field=models.CharField(choices=[('\u79d8\u4e66\u90e8', b'\xe7\xa7\x98\xe4\xb9\xa6\xe9\x83\xa8'), ('\u4eba\u529b\u8d44\u6e90\u90e8', b'\xe4\xba\xba\xe5\x8a\x9b\xe8\xb5\x84\xe6\xba\x90\xe9\x83\xa8'), ('\u5ba3\u4f20\u90e8', b'\xe5\xae\xa3\xe4\xbc\xa0\xe9\x83\xa8'), ('\u7ec4\u7ec7\u90e8', b'\xe7\xbb\x84\xe7\xbb\x87\xe9\x83\xa8')], default=b'\xe7\xbb\x84\xe7\xbb\x87\xe9\x83\xa8', max_length=12),
        ),
    ]
