# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20170726_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_model',
            name='member_id',
        ),
        migrations.AddField(
            model_name='post_model',
            name='author',
            field=models.CharField(default=b'NoBody', max_length=20),
        ),
        migrations.AlterField(
            model_name='post_model',
            name='section',
            field=models.CharField(choices=[('\u677f\u57571', b'\xe6\x9d\xbf\xe5\x9d\x971'), ('\u677f\u57572', b'\xe6\x9d\xbf\xe5\x9d\x972'), ('\u677f\u57573', b'\xe6\x9d\xbf\xe5\x9d\x973'), ('\u677f\u57574', b'\xe6\x9d\xbf\xe5\x9d\x974')], max_length=12),
        ),
    ]
