# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20170729_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cost', models.PositiveSmallIntegerField(default=0)),
                ('last_sign', models.DateTimeField(verbose_name=b'time')),
            ],
        ),
        migrations.AlterField(
            model_name='post_model',
            name='section',
            field=models.CharField(choices=[('\u5b66\u672f\u8ba8\u8bba\u533a', b'\xe5\xad\xa6\xe6\x9c\xaf\xe8\xae\xa8\xe8\xae\xba\xe5\x8c\xba'), ('\u90e8\u95e8\u4ea4\u6d41\u533a', b'\xe9\x83\xa8\xe9\x97\xa8\xe4\xba\xa4\xe6\xb5\x81\xe5\x8c\xba'), ('\u704c\u6c34\u533a', b'\xe7\x81\x8c\xe6\xb0\xb4\xe5\x8c\xba'), ('\u7cbe\u534e\u533a', b'\xe7\xb2\xbe\xe5\x8d\x8e\xe5\x8c\xba'), ('\u8d44\u6e90\u5171\u4eab\u533a', b'\xe8\xb5\x84\xe6\xba\x90\xe5\x85\xb1\xe4\xba\xab\xe5\x8c\xba')], max_length=12),
        ),
    ]
