# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20170803_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application_model',
            options={'verbose_name': 'Application Form'},
        ),
        migrations.AlterModelOptions(
            name='member_model',
            options={'verbose_name': 'Member'},
        ),
        migrations.RemoveField(
            model_name='member_model',
            name='costs',
        ),
        migrations.RemoveField(
            model_name='member_model',
            name='password',
        ),
    ]
