# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_auto_20170815_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_model',
            options={'verbose_name': 'post'},
        ),
    ]
