# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_auto_20170816_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_Upload_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to=b'')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Member_Model')),
            ],
        ),
    ]
