# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 16:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_member_upload_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2017, 8, 22, 16, 13, 59, 64678))),
                ('read_status', models.BooleanField(default=False)),
                ('content', models.CharField(max_length=10240)),
                ('msg_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_member', to='mysite.Member_Model')),
                ('msg_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_member', to='mysite.Member_Model')),
            ],
        ),
    ]
